### PR TITLE
Closes #510

### LINKED ISSUE #510: Debian Bullseye installs DHCP packages when "no" is given for DHCP
See this forum thread for details: https://forums.fogproject.org/topic/16565/installing-1-5-9-on-debian-bullseye-fails/2

When using dev-branch on Debian Bullseye, you say "no" for setting up DHCP, the installation script still installs the DHCP packages but does not configure or enable a DHCP server.

The bug is that the DHCP packages are installed but should not be.

### PR DESCRIPTION
**Pull request by lukebarone**
- Tested on fresh Debian Bullseye x64
- Shellchecked for new code (removing `$dhcpname` and `$dhcpd` from `$packages` array)

Install log indicates that `isc-dhcp-server` is NO LONGER being installed. The configuration step is also marked as "Skipped".

### CODE REVIEW

**Comment by lukebarone** [comment]
I'll get that done and push it out soon

**Comment by lukebarone** [comment]
Running through a test on a VM...

File: lib/redhat/config.sh [hunk 1]
```diff
@@ -83,5 +83,5 @@ fi
 [[ -z $dhcpconfigother ]] && dhcpconfigother="/etc/dhcp/dhcpd.conf"
 [[ -z $tftpdirdst ]] && tftpdirdst="/tftpboot"
 [[ -z $ftpconfig ]] && ftpconfig="/etc/vsftpd/vsftpd.conf"
-[[ -z $dhcp ]] && dhcpd="dhcpd"
```
Comment (Sebastian-Roth) [inline lib/redhat/config.sh:86]: Yeah, I stumbled that one as well but forgot to mention it. Nice find!

File: bin/installfog.sh [hunk 2]
```diff
@@ -542,16 +542,13 @@ while [[ -z $blGo ]]; do
...
+                newpackagelist=( "${packages[@]/$htmldoc}" )
                 packages="$(echo $newpackagelist)"
             fi
             if [[ $bldhcp == 0 ]]; then
                 [[ -z $newpackagelist ]] && newpackagelist=""
-                for z in $packages; do
-                    [[ $z != $dhcpname ]] && newpackagelist="$newpackagelist $z"
-                done
+                newpackagelist=( "${packages[@]/$dhcpname}" )
+                # Additional check for Debian/Ubuntu variants
```
Comment (Sebastian-Roth) [inline bin/installfog.sh:551]: Do we actually need this comment anymore? Hope this doesn't sound bossy.

**Review by Sebastian-Roth — APPROVED** [review]
I wouldn't mind merging this even with that comment included. But if you find a minute to remove it, I wouldn't mind either. I will merge this tomorrow if I don't hear back from you until then. Thanks.

File: bin/installfog.sh (hunk 2 above)
Comment (lukebarone) [reply bin/installfog.sh]: Resolved via a11ce8b
